# <center>NumPy的ndarray:一种对维数组对象</center>

ndarray,即n维数组。该对象是一个快速而灵活的大数据集容器。

ndarray是一个通用的同结构数据多维容器。

### 0. 准备工作

In [1]:
%matplotlib inline

In [2]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [3]:
# 随机生成一个2*3的数组
data = randn(2, 3)

In [4]:
data

array([[ 1.0485,  1.1866, -0.4595],
       [-1.6537, -0.1735,  0.7875]])

In [5]:
data * 10

array([[ 10.4846,  11.8661,  -4.5951],
       [-16.5374,  -1.7346,   7.8746]])

In [6]:
data + data

array([[ 2.0969,  2.3732, -0.919 ],
       [-3.3075, -0.3469,  1.5749]])

每个数组都有一个shape**(一个表示各维度大小的元组)**和dtype**(一个用于说明数组数据类型的对象)**

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

**由于NumPy关注的是数值计算，因此，如果没有特别指定，数据类型基本都是float64。**

### 1.1创建ndarray

In [9]:
# 普通的一维数组
data1 = [6, 7, 5, 8, 0, 1]

In [10]:
# 将list转化为NumPy数组
arr1 = np.array(data1)

In [11]:
arr1

array([6, 7, 5, 8, 0, 1])

In [12]:
# 1D数组中，会省略显示维度
arr1.shape

(6,)

In [13]:
arr1.ndim

1

In [14]:
# 普通的二维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# 数组维数
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('int32')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
# 创建一个全0的数组，默认为一维数组
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
# args:维数，每一维的个数
np.zeros((1, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [23]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [24]:
np.empty((2, 3, 2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 1.2ndarray的数据类型

In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([ 1.,  2.,  3.])

In [27]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3])

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

ndarray的astype方法显示地转换其dtype

In [30]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [31]:
arr.dtype

dtype('int32')

In [32]:
# 类型转换
float_arr = arr.astype(np.float64)
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [33]:
float_arr.dtype

dtype('float64')

浮点数转换成整数，则小数部分将会被截段

In [34]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [35]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [36]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [37]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [38]:
numeric_strings.astype(float) # 不规范写法，应写成 np.float64

array([  1.25,  -9.6 ,  42.  ])

In [39]:
int_array = np.arange(10)

In [40]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [41]:
# 整型转换成浮点型
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [42]:
empty_uint32 = np.empty(8, dtype='u4')

In [43]:
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### 1.3数组和标量(矢量)之间的运算

In [44]:
# 创建一个2D3轴的标量
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [45]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

不需要编写循环即可对数据执行批量运算

In [46]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [47]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [48]:
1 / arr

array([[ 1.    ,  0.5   ,  0.3333],
       [ 0.25  ,  0.2   ,  0.1667]])

In [49]:
arr * 0.5

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

### 1.4基本的索引和切片

一维数组与Python列表的功能差不多

In [50]:
arr = np.arange(10)

In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr[5]

5

In [53]:
arr[5:8]

array([5, 6, 7])

In [54]:
# 给切片中的值重新赋值
arr[5:8] = 12

In [55]:
# 源数组被修改了
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [56]:
l = list(range(10))
l_slice = l[5:8]
#l[5:8] = 12 # 不允许这样操作
# l_slice[1] = 12345
# Python列表中对切片操作，不会影响列表的值
# l

In [57]:
arr_slice = arr[5:8]

In [58]:
# 重新赋值
arr_slice[1] = 12345

In [59]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [60]:
arr_slice[:] = 64

In [61]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [62]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [63]:
# 在一个二维数组中，各索引位置上的元素不再是标量而是一维数组
arr2d[2]

array([7, 8, 9])

In [64]:
arr2d[0][2]

3

In [65]:
arr2d[0, 2]

3

多维数组

In [66]:
# 创建2*2*3的数组，即3d,
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

In [67]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr2d.ndim

2

In [69]:
arr2d.shape

(3, 3)

In [70]:
arr3d.ndim

3

In [71]:
arr3d.shape

(2, 2, 3)

In [72]:
# 3d数组中的元素是一个2*3的数组
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# 标量和数值都可以被赋值给arr3d[0]
old_values = arr3d[0].copy()

In [74]:
arr3d[0] = 42

In [75]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[0] = old_values

In [77]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
arr3d[1, 0]

array([7, 8, 9])

切片索引

In [79]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [80]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
# 前两行，1列开始
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [83]:
arr2d[1, :2]

array([4, 5])

In [84]:
arr2d[2, :1]

array([7])

In [85]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [86]:
arr2d[:2, 1:] = 0

In [87]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 1.5布尔型索引

In [88]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [89]:
data = randn(7, 4)

In [90]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [91]:
data

array([[ 0.5033, -0.8835,  0.7267,  0.4162],
       [-1.2   , -0.9859,  0.5702,  1.9839],
       [ 0.0645, -0.1587,  0.0504,  0.374 ],
       [-0.1965, -0.7599,  0.0807,  1.4532],
       [ 1.0564,  1.3819,  2.2318, -0.6105],
       [-1.9868,  0.2609,  0.091 , -1.8672],
       [ 0.4546, -0.0172, -0.5231, -1.336 ]])

In [92]:
names =='Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [93]:
data[names=='Bob'] # 两个 True

array([[ 0.5033, -0.8835,  0.7267,  0.4162],
       [-0.1965, -0.7599,  0.0807,  1.4532]])

In [94]:
data[names=='Bob', 2:] # 切片

array([[ 0.7267,  0.4162],
       [ 0.0807,  1.4532]])

In [95]:
data[names=='Bob', 3] # 索引

array([ 0.4162,  1.4532])

In [96]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [97]:
data[~(names=='Bob')]

array([[-1.2   , -0.9859,  0.5702,  1.9839],
       [ 0.0645, -0.1587,  0.0504,  0.374 ],
       [ 1.0564,  1.3819,  2.2318, -0.6105],
       [-1.9868,  0.2609,  0.091 , -1.8672],
       [ 0.4546, -0.0172, -0.5231, -1.336 ]])

In [98]:
mask = (names=='Bob') | (names=='Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [99]:
data[mask]

array([[ 0.5033, -0.8835,  0.7267,  0.4162],
       [ 0.0645, -0.1587,  0.0504,  0.374 ],
       [-0.1965, -0.7599,  0.0807,  1.4532],
       [ 1.0564,  1.3819,  2.2318, -0.6105]])

通过布尔型数组设置元素的值是一种常用的手段

In [100]:
data[data<0]=0
data

array([[ 0.5033,  0.    ,  0.7267,  0.4162],
       [ 0.    ,  0.    ,  0.5702,  1.9839],
       [ 0.0645,  0.    ,  0.0504,  0.374 ],
       [ 0.    ,  0.    ,  0.0807,  1.4532],
       [ 1.0564,  1.3819,  2.2318,  0.    ],
       [ 0.    ,  0.2609,  0.091 ,  0.    ],
       [ 0.4546,  0.    ,  0.    ,  0.    ]])

In [101]:
data[names!='Joe']=7
data

array([[ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.    ,  0.    ,  0.5702,  1.9839],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 7.    ,  7.    ,  7.    ,  7.    ],
       [ 0.    ,  0.2609,  0.091 ,  0.    ],
       [ 0.4546,  0.    ,  0.    ,  0.    ]])

### 1.6 花式索引
是指利用整数数组进行索引

In [102]:
arr = np.empty((8, 4))

In [103]:
for i in range(8):
    arr[i] = i

In [104]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

通过索引，选取特定顺序的行子集

In [105]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [106]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [107]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [108]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [109]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [110]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 1.7数组转置和轴对称

In [111]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [112]:
# 数组的转置
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

进行矩阵的内积运算

In [113]:
# 二维矩阵
arr = np.random.randn(6, 3)

In [114]:
np.dot(arr.T, arr)

array([[  1.2203,  -0.133 ,   1.6451],
       [ -0.133 ,   5.0641,  -3.9735],
       [  1.6451,  -3.9735,  12.0099]])

**高维数组**

In [115]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [116]:
# 高维数组的转置
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [117]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [118]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])