# <center>通用函数：快速的元素级数组函数</center>

Universal Functions: Fast element-wise array functions

通用函数(ufunc)是一种对ndarray中的数据执行元素级运算的函数

### 0.准备工作

In [1]:
%matplotlib inline

In [2]:
from __future__ import division
from numpy.random import randn
import numpy as np
np.set_printoptions(precision=4, suppress=True)

许多ufunc都是简单的元素级变体，这类ufunc称为一元通用函数(unary ufunc)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 求各元素的平方根
np.sqrt(arr)

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 各元素的指数e^x
np.exp(arr)

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

有的通用函数接受两个数组，这类ufunc称为二元通用函数(binary ufunc)

In [8]:
x = randn(8)
y = randn(8)

In [9]:
x

array([-0.165 ,  2.2289, -0.2138,  0.0079,  1.6029,  0.7952, -1.2973,
        0.1744])

In [10]:
y

array([ 0.743 ,  0.958 ,  0.2479, -0.3373,  0.7713,  0.3249, -1.4511,
        0.5342])

In [11]:
# 元素级最大值
np.maximum(x, y)

array([ 0.743 ,  2.2289,  0.2479,  0.0079,  1.6029,  0.7952, -1.2973,
        0.5342])

In [12]:
arr = randn(7) * 5

In [13]:
np.modf(arr)

(array([ 0.3603, -0.4553, -0.911 , -0.3946,  0.9132, -0.3875, -0.6656]),
 array([ 3., -0., -0., -2.,  2., -6., -2.]))

---

## <center>附录：常用用函数的用法说明</center>

### 一元ufunc

|函数|作用|说明|
|--|--|--|
|abs、fabs|计算整数、浮点数或者复数的绝对值|对于非复数值，可以使用更快的fabs|
|sqrt|计算各元素的平方根|相当于arr**0.5|
|square|计算各元素的平方|相当于arr**2|
|exp|计算各元素的指数e^x||
|log、log10、log2、log1p|分别为自然对数(e)、底数为10的log。底数为2的log、log(1+x)||
|sign|符号函数，计算各元素的正负号|1(正数)、0(零)、-1(负数)|
|ceil|计算各元素的ceiling值|即大于等于该值的最小整数|
|floor|计算各元素的floor值|即小于等于该值的最大整数|
|rint|将各元素值四舍五入到最接近的整数，保留原有的dtype||
|modf|将数组的小数部分和整数部分以两个独立数组的形式返回||
|isnan|返回一个表示"哪些值是NaN"的布尔数组||
|isfinite、isinf|分别返回一个表示"哪些元素是有穷的"或者"哪些元素是无穷的"的布尔型的数组||
|cos、cosh、sin、sinh、tan、tanh|普通型和双曲型三角函数||
|arccos、arccosh、arcsin、arcsinh、arctan、arctanh|反三角函数||
|logic_not|计算各元素not x的真值|相当于-arr|

### 二元ufunc

|函数|作用|说明|
|--|--|--|
|add|将数组中对应的元素相加||
|subtract|从第一个数组中减去第二个数组中的元素||
|muiltiply|数组元素相乘||
|divide、floor_divide|除法或者向下整除||
|power|第一个数组元素A,第二个数组元素B，计算A**B||
|maximum、fmax|元素级的最大值|fmax将忽略NaN|
|minimum、fmin|元素级的最小值|fmin将忽略NaN|
|mod|元素级的取模计算||
|copysign|将第二个数组中的值的符号，复制给第一个数组中值|变正负号|
|greater、greater_equal、less、less_equal、equal、not_equal|比较运算|相当于运算符>、>=、<、<=、==、!=|
|logical_and、logical_or、logical_xor|逻辑运算|与(&)、或(丨)、异或(^)|