# <center>Numpy基础</center>

Numpy是Python机器学习技术栈的基础。Numpy能对机器学习中常用的数据结构-向量(Vector)、矩阵(matrice)、张量(tensor)进行高效操作。

---
## <center>基本属性</center>

### 1.1 创建一个向量

In [1]:
# 在Python中用一个数组来表示一个向量
import numpy as np

# 创建一个行向量
vector_row = np.array([1,2,3])
# 创建一个列向量
vector_column = np.array([[1],
                          [2],
                          [3]])

In [2]:
vector_row

array([1, 2, 3])

In [3]:
vector_column

array([[1],
       [2],
       [3]])

### 1.2 创建一个矩阵

In [4]:
matrix = np.array([[1,2],
                   [1,2],
                   [1,2]])

In [5]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [6]:
# 创建一个全0的数组，默认为一维数组
zeros = np.zeros(10)

In [7]:
zeros

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
# args:维数，每一维的个数
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

### 1.3 创建一个稀疏矩阵

In [9]:
from scipy import sparse

matrix = np.array([[0,0],
                   [0,1],
                   [3,0]])
# 创建一个压缩的稀疏行矩阵
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


### 1.4 选择元素

In [10]:
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [11]:
# 切片
vector[2]

3

In [12]:
matrix[1,1]

5

### 1.5 显示矩阵的属性

In [13]:
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [14]:
matrix.shape

(3, 4)

In [15]:
matrix.size

12

In [16]:
matrix.ndim

2

In [17]:
matrix.dtype

dtype('int32')

---
## <center>数组元素的运算</center>
通用函数(ufunc)是一种对ndarray中的数据执行元素级运算的函数

### 1.6 对多个元素同时应用某个操作

In [18]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

**使用广播的方法**

In [90]:
matrix + 100

array([[101, 104],
       [102, 105]])

In [20]:
matrix * matrix

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [21]:
1 / matrix

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667],
       [ 0.14285714,  0.125     ,  0.11111111]])

**使用向量化函数的方法**

In [89]:
# 创建匿名函数
add_100 = lambda i:i+100
# 创建向量化函数
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 104],
       [102, 105]])

**通用函数**

In [22]:
# 求各元素的平方根
np.sqrt(matrix)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974],
       [ 2.64575131,  2.82842712,  3.        ]])

In [23]:
# 各元素的指数e^x
np.exp(matrix)

array([[  2.71828183e+00,   7.38905610e+00,   2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02],
       [  1.09663316e+03,   2.98095799e+03,   8.10308393e+03]])

有的通用函数接受两个数组，这类ufunc称为**二元通用函数(binary ufunc)**

In [28]:
from numpy.random import randn

x = randn(8)
y = randn(8)

In [29]:
x

array([ 0.77501601,  0.96983011, -0.85734675,  1.44267774, -0.77490051,
       -1.56292782,  1.84566829,  1.10124819])

In [30]:
y

array([ 0.10288543, -0.35360404, -0.41142472,  1.25815514,  0.65719648,
       -0.02143657, -0.65359593,  0.71667927])

In [31]:
# 元素级最大值
np.maximum(x, y)

array([ 0.77501601,  0.96983011, -0.41142472,  1.44267774,  0.65719648,
       -0.02143657,  1.84566829,  1.10124819])

更多常用通用函数，见附录一

---
## <center>数学和统计方法</center>
可以通过数组上的一组数学函数地整个数组或者某个轴向的数据进行统计计算。

### 1.7 找到最大值和最小值

In [32]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [33]:
np.max(matrix)

9

In [34]:
np.min(matrix)

1

**对特定的坐标轴进行求最大值和最小值**

使用axis参数,axis=0,表示列操作；axis=1,表示行操作。

In [35]:
# 找到每一列最大的元素
np.max(matrix, axis=0)

array([7, 8, 9])

In [36]:
# 找到每一行最大的元素
np.max(matrix, axis=1)

array([3, 6, 9])

### 1.8 计算求和、平均值、方差和标准差

In [37]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [38]:
np.sum(matrix)

45

In [39]:
np.mean(matrix)

5.0

In [40]:
np.var(matrix)

6.666666666666667

In [41]:
np.std(matrix)

2.5819888974716112

In [42]:
# 列向量求和
np.sum(matrix, axis=0)

array([12, 15, 18])

In [43]:
# 行向量求和
np.sum(matrix, axis=1)

array([ 6, 15, 24])

### 1.9 对数组进行排序
NumPy数组也可以通过sort方法进行从小到大排序

In [44]:
arr = randn(8)
arr

array([ 1.05088702,  1.77801942, -0.24938901,  0.89297512,  0.95842243,
        0.57993658, -1.64972832,  0.08291242])

In [45]:
arr.sort()
arr

array([-1.64972832, -0.24938901,  0.08291242,  0.57993658,  0.89297512,
        0.95842243,  1.05088702,  1.77801942])

对于**多维数组**可以在任意一个轴向上进行排序，只需将轴的编号传给sort即可。<br>
使用axis参数,axis=0,表示列操作；axis=1,表示行操作。

In [46]:
arr = randn(5, 3)
arr

array([[ 1.44012092,  0.25471866,  1.13037248],
       [ 1.41238878, -1.39837575, -0.5800484 ],
       [ 2.00900838, -0.26426969,  0.91018108],
       [ 0.84610625,  0.29531145,  1.05328791],
       [ 1.41285474,  0.94893268, -0.95147426]])

In [47]:
# 列排序
arr.sort(0)
arr

array([[ 0.84610625, -1.39837575, -0.95147426],
       [ 1.41238878, -0.26426969, -0.5800484 ],
       [ 1.41285474,  0.25471866,  0.91018108],
       [ 1.44012092,  0.29531145,  1.05328791],
       [ 2.00900838,  0.94893268,  1.13037248]])

In [48]:
# 行排序
arr.sort(1)
arr

array([[-1.39837575, -0.95147426,  0.84610625],
       [-0.5800484 , -0.26426969,  1.41238878],
       [ 0.25471866,  0.91018108,  1.41285474],
       [ 0.29531145,  1.05328791,  1.44012092],
       [ 0.94893268,  1.13037248,  2.00900838]])

### 1.10 数组中元素的集合操作
np.unique方法用于找出数组中的唯一值并返回已排序结果

In [49]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

In [50]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

np.in1d方法用于测试一个数组中的值在另一个数组中的成员资格，即该值是否出现在另一个数组

In [51]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

更多数组统计方法，见附录二

---
## <center>矩阵相关</center>
numpy.linalg模块包含线性代数的函数。使用这个模块，可以计算逆矩阵、求特征值、解线性方程组以及求解行列式等。

### 1.11 矩阵变形
在不改变元素值的前提下，改变一个数组的形状

In [52]:
# 一个3*4矩阵
matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [53]:
# 将矩阵变形为2*6的矩阵
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### 1.12 转置

In [54]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [55]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**行向量与列向量**

In [56]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [57]:
arr1.shape

(6,)

In [58]:
arr1.T

array([1, 2, 3, 4, 5, 6])

In [59]:
# 注意第2对括号
arr2 = np.array([[1,2,3,4,5,6]])

In [60]:
arr2.shape

(1, 6)

In [61]:
arr2.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 1.13 将矩阵展开成一维数组

In [62]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.14 计算矩阵的秩

In [63]:
matrix = np.array([[1,1,1],
                   [1,1,10],
                   [1,1,15]])
np.linalg.matrix_rank(matrix)

2

### 1.15 计算矩阵对应的行列式

In [64]:
matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,6,9]])
np.linalg.det(matrix)

0.0

### 1.16 获取矩阵的对角线元素

In [65]:
matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,6,9]])
matrix.diagonal()

array([1, 4, 9])

### 1.17 计算矩阵的迹

In [66]:
matrix = np.array([[1,2,3],
                   [2,4,6],
                   [3,6,9]])
matrix.trace()

14

### 1.18 计算特征值和特征向量

In [67]:
matrix = np.array([[1,-1,3],
                   [1,1,6],
                   [3,8,9]])
# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [68]:
eigenvalues

array([ 13.55075847,   0.74003145,  -3.29078992])

In [69]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

### 1.19 计算点积

In [70]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# 计算点积
np.dot(vector_a, vector_b)

32

### 1.20 矩阵的加减运算

In [71]:
matrix_a = np.array([[1,1,1],
                     [1,1,1],
                     [1,1,2]])
matrix_b = np.array([[1,3,1],
                     [1,3,1],
                     [1,3,8]])

In [72]:
# 矩阵相加
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [73]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [74]:
# 矩阵相减
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [75]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

### np.add()与+运算符的区别
在Python语法中，a+b被翻译为a.\__add\__(b)。 a.\__add\__是一种为a类型的对象实现添加的方法。数字有这样的方法，列表也有（[1,3]+[4]），字符串也是如此（'abc'+'d'）。

numpy已为其\__add\__类实施了\__...（以及其他标准ndarray方法）（至少对于数字dtypes）。

这是所有标准的Python和numpy并且永远存在。

np.add是ufunc。查看其文档 - 请参阅out参数和Binary ufuncs:部分。它是一个函数，并且有一些方法，如reduce，reduceat等a.\__add\__（和+）没有。

**总结**
1. 同型矩阵
    对于两个/两个以上的同型矩阵进行运算时，np.add()与 + 的运算方式的速度基本没有区别，使用“+”号还是np.add()命令都可以。
2. 不同型矩阵
    np.add()与 + 完全不同，尤其是在进行**广播**运算时。

In [76]:
# default list concatenation
[1,2,3]+[4]

[1, 2, 3, 4]

In [77]:
# convert lists to arrays and sum
np.add([1,2,3],[4])

array([5, 6, 7])

**使用2d广播**

In [78]:
np.add([[1],[2],[3]],[4,1])

array([[5, 2],
       [6, 3],
       [7, 4]])

In [79]:
np.array([1,2,3])[:,None]+np.array([4,1])

array([[5, 2],
       [6, 3],
       [7, 4]])

### 1.21 矩阵的乘法

In [80]:
matrix_a = np.array([[1,1],
                     [1,2]])
matrix_b = np.array([[1,3],
                     [1,2]])

In [81]:
# 矩阵相乘
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

**对于同型矩阵。可以直接使用操作符**

In [82]:
# Python 3.5以上支持使用 "@" 操作符
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

**"*" 操作符仅仅是矩阵对应元素相乘**

In [83]:
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

### 1.22 计算矩阵的逆

In [84]:
matrix = np.array([[1,4],
                   [2,5]])
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [85]:
np.dot(matrix, np.linalg.inv(matrix))

array([[ 1.,  0.],
       [ 0.,  1.]])

---
## <center>随机数</center>

### 1.23 生成随机数

In [86]:
# 设置随机种子
np.random.seed(0)

# 生成3个随机数
np.random.random(3)

array([ 0.5488135 ,  0.71518937,  0.60276338])

#### 更多的时候，我们需要生成整数随机数

In [87]:
# 生成3个0到10之间的随机数
np.random.randint(0, 11, 3)

array([3, 7, 9])

#### 也可以从概率分布中抽取一些数来生随机数

In [88]:
# 从标准正态分布中抽取3个数
np.random.normal(0.0, 1.0, 3)# 第一个参数为均值，第二个参数为标准差，第三个参数为随机数的数量

array([-1.42232584,  1.52006949, -0.29139398])

## <center>附录一：常用用函数的用法说明</center>

### 一元ufunc

|函数|作用|说明|
|--|--|--|
|abs、fabs|计算整数、浮点数或者复数的绝对值|对于非复数值，可以使用更快的fabs|
|sqrt|计算各元素的平方根|相当于arr**0.5|
|square|计算各元素的平方|相当于arr**2|
|exp|计算各元素的指数e^x||
|log、log10、log2、log1p|分别为自然对数(e)、底数为10的log。底数为2的log、log(1+x)||
|sign|符号函数，计算各元素的正负号|1(正数)、0(零)、-1(负数)|
|ceil|计算各元素的ceiling值|即大于等于该值的最小整数|
|floor|计算各元素的floor值|即小于等于该值的最大整数|
|rint|将各元素值四舍五入到最接近的整数，保留原有的dtype||
|modf|将数组的小数部分和整数部分以两个独立数组的形式返回||
|isnan|返回一个表示"哪些值是NaN"的布尔数组||
|isfinite、isinf|分别返回一个表示"哪些元素是有穷的"或者"哪些元素是无穷的"的布尔型的数组||
|cos、cosh、sin、sinh、tan、tanh|普通型和双曲型三角函数||
|arccos、arccosh、arcsin、arcsinh、arctan、arctanh|反三角函数||
|logic_not|计算各元素not x的真值|相当于-arr|

### 二元ufunc

|函数|作用|说明|
|--|--|--|
|add|将数组中对应的元素相加||
|subtract|从第一个数组中减去第二个数组中的元素||
|muiltiply|数组元素相乘||
|divide、floor_divide|除法或者向下整除||
|power|第一个数组元素A,第二个数组元素B，计算A**B||
|maximum、fmax|元素级的最大值|fmax将忽略NaN|
|minimum、fmin|元素级的最小值|fmin将忽略NaN|
|mod|元素级的取模计算||
|copysign|将第二个数组中的值的符号，复制给第一个数组中值|变正负号|
|greater、greater_equal、less、less_equal、equal、not_equal|比较运算|相当于运算符>、>=、<、<=、==、!=|
|logical_and、logical_or、logical_xor|逻辑运算|与(&)、或(丨)、异或(^)|

---
## <center>附录二：基本数组统计方法</center>

|方法|作用|说明|
|-|-||
|sum|对数组中全部或者某个轴向的元素求和|零长度的数组的sum为0|
|mean|算术平均数|零长度的数组的mean为NaN|
|std、var|分别为标准差和方差|自由度可调|
|min、max|最小值和最大值||
|argmin、argmax|分别求出最小元素和最大元素的索引||
|cumsum|所有元素的累计和|返回沿给定轴的元素的累积和|
|cumprod|所有元素的累计积|返回沿给定轴的元素的累积和|